### ISSUE TITLE
code usage

### ISSUE THREAD

**Issue by gurugeek** [pres220/top-100-german-verbs#1]
First of all thanks for the excellent app! I made some changes (most notably style to make it an iOS PWA to be easily linkable as an app on iOS devices) and published it at 
https://deutsch.link 
In planning there is also to add Django Rest Framework to it. 

I am not sure if the credits are correct but it is all it was available on GitHub 🤔 let me know if this is fine or to whom I should give proper attribution.. Also there is no license on the repository so I assumed it was available for forking/public usage. Do let me know if this is not the case.

**Comment by pres220** [comment]
Hello,

Thanks for your interest and for bringing the licensing issue to my attention. I've added the MIT License to the repository. The credit info is also fine with me.
